import Head from "next/head";
import "../styles/globals.css";

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Airbnb</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://cdn.freelogovectors.net/wp-content/uploads/2016/12/airbnb_logo.png"
        />
      </Head>
      <Component {...pageProps} />
    </>
  );
}

export default MyApp;
